#!/usr/bin/perl
use strict;
use warnings;

# This code was generated by claude.ai with the promt:
# I have a list of 5000 x,y coordinates and need to select the two
# that enclose the largest area. Write some efficient Perl code to solve please.
 
# Read coordinates from input
# Expected format: one coordinate per line as "x,y" or "x y"
my @points;
while (<>) {
    chomp;
    my ($x, $y) = split /[,\s]+/;
    push @points, [$x, $y];
}

# Find the bounding box that maximizes area
my $max_area = 0;
my ($best_p1, $best_p2);

# For axis-aligned rectangles, we need points with different x and y values
# This is O(n²) but necessary to check all pairs
for my $i (0 .. $#points - 1) {
    for my $j ($i + 1 .. $#points) {
        my ($x1, $y1) = @{$points[$i]};
        my ($x2, $y2) = @{$points[$j]};
        
        # Calculate area of axis-aligned rectangle
        my $width = abs($x2 - $x1) + 1;
        my $height = abs($y2 - $y1) + 1;
        my $area = $width * $height;
        
        if ($area > $max_area) {
            $max_area = $area;
            $best_p1 = $points[$i];
            $best_p2 = $points[$j];
        }
    }
}

# Output results
print "Maximum area: $max_area\n";
print "Point 1: ($best_p1->[0], $best_p1->[1])\n";
print "Point 2: ($best_p2->[0], $best_p2->[1])\n";
